site_name: Part writing Error Checker
nav:
    - Home: 'index.md'
    - Installation: 'installation.md'
    - Running: 'running.md'
    - Partwriting Errors: '/Errors/'
    - Key Decisions: 'keydecisions.md'
    - Notes: 'interestingnotes.md'
    - Credits: 'credits.md'
theme: readthedocs
