site_name: Part Writing Error Checker
site_url: https://honorscapstoneproject.readthedocs.io/
theme: readthedocs
nav:
  - Home: 'README.md'
  - Installation: 'Installation.md'
  - Running: 'Running.md'
  - Errors:
    - 'Parallel Errors': 'Errors/ParallelErrors.md'
    - 'Range Errors': 'Errors/RangeErrors.md'
    - 'Spacing Errors': 'Errors/SpacingErrors.md'
    - 'Crossed Voices': 'Errors/CrossedVoices.md'
    - 'Melodic Dissonance': 'Errors/MelodicDissonance.md'
  - Development:
    - 'Key Decisions': 'KeyDecisions.md'
    - 'Interesting Notes': 'InterestingNotes.md'
    - 'Future Work': 'FutureWork.md'
    - 'Credits': 'Credits.md'
